const testimonials = [
    {
      name: "Kunwar Atharav",
      role: "Recruiter - Repaybly",
      imageSrc: "https://www.dropbox.com/scl/fi/sfy9cwsvphx5fkpjqgd0e/1641222004297.jpeg?rlkey=9sj1ntl6zoh0j6m1vb198cfrd&dl=1",
      testimonialText: "Anshika was the linchpin of my startup, excelling as the senior front-end developer. Her unmatched technical skills, reliability, and effective communication significantly elevated our projects. I wholeheartedly recommend Anshika for her invaluable contributions in our venture.",
      socialLinks: {
        github: null,
        facebook: null,
        linkedin: "https://www.linkedin.com/in/kunwar-atharav-singh-kotwal-3b4930220/",
        instagram: null,
        twitter: null,
        email: "mailto:atharavsingh2002@gmail.com",
      },
    },
    {
        name: "Himanshu Goyal",
        role: "Design Lead - Hackoverflow Society",
        imageSrc: "https://www.dropbox.com/scl/fi/ntd4xgr4980e0wtxp85r0/1677180050620.jpeg?rlkey=41dm6pgtjah2ohw7mknnqukeb&dl=1",
        testimonialText: "Working with Anshika has been the best decision. Their attention to detail, creative approach to design, and proficiency in front-end technologies have significantly contributed to the success of our projects. Their dedication to delivering high-quality and visually stunning user interfaces sets them apart. I highly recommend Anshika for anyone seeking a skilled and reliable front-end developer.",
        socialLinks: {
          github: null,
          facebook: null,
          linkedin: "https://www.linkedin.com/in/himanshu-goyal-b2376232/",
          instagram: "https://www.instagram.com/hg_569/",
          twitter: null,
          email: "mailto:atharavsingh2002@gmail.com",
        },
      },
    
      {
        name: "Ishika Dixit",
        role: "Design Lead - LaDebug Club",
        imageSrc: "https://www.dropbox.com/scl/fi/7ojpjbtybnl0yh0vy9i1s/1643613920484.jpeg?rlkey=3sg6ffom6zz9pk1avefi2rv12&dl=1",
        testimonialText: "I worked with Anshika at LaDebug Club & HackOverflow Society, where her skills as a Frontend Developer were invaluable. Her ability to transform complex designs into intuitive interfaces was impressive. Anshika's teamwork, problem-solving skills, and commitment to deadlines greatly contributed to our projects. Her talents and positive attitude make her an asset to any team.",
        socialLinks: {
          github: null,
          facebook: null,
          linkedin: "https://linkedin.com/in/girlwithalaptop/",
          instagram: "https://www.instagram.com/_ishikadixit_/",
          twitter: null,
          email: "mailto:ishika.dixit.work@gmail.com",
        },
      },
      {
        name: "Shashank ",
        role: "Internal Secretary - Hackoverflow Society",
        imageSrc: "https://www.dropbox.com/scl/fi/iaheimxwrsa5r6lig6ba0/1697046643456.jpeg?rlkey=kojvpa7zxsnm00pjet4i7eltw&dl=1",
        testimonialText: "Anshika is one of the best front end developers that I've ever worked with. No matter what I've designed, I'm always confident that she can bring my designs to iife it the same manner from pixel to pixel through her coding skills",
        socialLinks: {
          github: null,
          facebook: null,
          linkedin: "https://www.linkedin.com/in/sha-shanks/",
          instagram: "https://www.instagram.com/your.guy.shanks/",
          twitter: null,
          email: "mailto:shashank000283@gmail.com",
        },
      },
      {
        name: "Krishma Kaur",
        role: "Chief Executive Member - LaDebug Club",
        imageSrc: "https://www.dropbox.com/scl/fi/aqusfrwq41dfbcilhsu5w/1673614670436.jpeg?rlkey=09jakkrm6ej0hpo11lqadgxrg&dl=1",
        testimonialText: "She has made a significant contribution to the organization with her genuine efforts. She is well trained in developing, maintaining and designing websites. Her work has exceeded our expectations. Her talent in creating stunning and memorable website designs is simply remarkable. She demonstrated professionalism, patience, and attention to detail during her time with us. We are pleased with her work and highly recommend her services as a web developer.",
        socialLinks: {
          github: null,
          facebook: null,
          linkedin: "https://www.linkedin.com/in/krishma7/",
          instagram: "https://www.instagram.com/__krishma.__/",
          twitter: null,
          email: "mailto:krishma.clubladebug@gmail.com",
        },
      },
      {
        name: "Sudhir Verma",
        role: "Recruiter - JPF NGO",
        imageSrc: "",
        testimonialText: "Thanks for your talent and hard work, JPF NGO now has a compelling online presence that effectively communicates our cause to the world. I wholeheartedly recommend anshika for any web design or development project; she's a true professional and a pleasure to collaborate with.",
        socialLinks: {
          github: null,
          facebook: null,
          linkedin: "https://www.linkedin.com/in/sudhir-kumar-verma-46a661108/",
          instagram: "https://www.instagram.com/fetcher.dev",
          twitter: null,
          email: "mailto:sudhirkumar.verma108@gmail.com",
        },
      },
      {
        name: "Amardeep Kesharwani",
        role: "SE - DVertex ",
        imageSrc: "https://www.dropbox.com/scl/fi/jq9ld6xsh25ranl7c49qq/1696250781381.jpeg?rlkey=sc7se1olcpxykvsz88excrerw&dl=1",
        testimonialText: "",
        socialLinks: {
          github: "https://github.com/amardeepkesharwani",
          facebook: null,
          linkedin: "https://www.linkedin.com/in/amardeepkesharwani/",
          instagram: "https://www.instagram.com/amardeep_kesharwani",
          twitter: null,
          email: null,
        },
      },
      {
        name: "Tanay Bhatt",
        role: "FreeLancer",
        imageSrc: "",
        testimonialText: "I am thrilled to provide a strong endorsement for Anshika, a standout freelance frontend developer. Anshika's expertise in React, and Tailwind, coupled with a keen design sense, consistently elevates the quality of our projects. Her commitment to timely delivery, collaborative approach, and innovative thinking make her an invaluable freelancer. Anshika's professionalism and dedication to excellence truly set her apart in the world of frontend development",
        socialLinks: {
          github: "",
          facebook: null,
          linkedin: "",
          instagram: "https://www.instagram.com/bhatt_tanay/",
          twitter: null,
          email: "mailto:",
        },
      },
      {
        name: "Ashwini Gupta",
        role: "SE - TCS",
        imageSrc: "https://www.dropbox.com/scl/fi/xw993quykgqueyffbsebv/1688456716883.jpeg?rlkey=acv0aupad5qv87y5gwj1f0xk6&dl=1",
        testimonialText: "Anshika is an outstanding frontend developer whose skills have greatly enhanced our projects. With an exceptional eye for design and a deep understanding of user experience, she transforms complex ideas into visually stunning and intuitive interfaces. Anshika's proficiency in Reactjs and Tailwind, coupled with her commitment to delivering high-quality work on time, sets her apart. Her passion for staying current with industry trends ensures our projects remain cutting-edge. Anshika is a true professional, and I wholeheartedly recommend her to anyone in need of a top-tier frontend developer",
        socialLinks: {
          github: "",
          facebook: null,
          linkedin: "https://www.linkedin.com/in/ashwani-gupta-5658b61bb",
          instagram: "https://www.instagram.com/ashwanigpt333/",
          twitter: null,
          email: "mailto:ashwanigpt13@gmail.com",
        },
      },
      {
        name: "Prasant Kumar",
        role: "Frontend Dev",
        imageSrc: "https://www.dropbox.com/scl/fi/aamg38qsk9b1jmivjjhnc/1701466616218.jpeg?rlkey=zhdi6inzgeur8342j7xpb2tii&dl=1",
        testimonialText: "Anshika is great at building websites, turning ideas into beautiful, functional sites. Her coding and design skills are top-notch. I've seen her coding skills improve a lot. She's leveling up, and it's awesome to witness! Her passion for what she does makes her work stand out.",
        socialLinks: {
          github: "https://github.com/theprasant",
          facebook: null,
          linkedin: "https://www.linkedin.com/in/decodeprasant",
          instagram: "https://www.instagram.com/decodeprasant/",
          twitter: null,
          email: "mailto:",
        },
      },
    // Add more testimonials as needed
  ];
  
  export default testimonials;
  